# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-FileCopyrightText: 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # Docker base images
  - package-ecosystem: docker
    directory: /src/s-core-devcontainer/.devcontainer
    schedule:
      interval: daily
    groups:
      all-in-one:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # DevContainer
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
