# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: devcontainer-lock.json
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: [--maxkb=50, --enforce-all] # increase or add git lfs if too strict
  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 38980559e3a605691d6579f96222c30778e5a69e # 3.0.0
    hooks:
      - id: shellcheck
# - repo: local
#   hooks:
#     - id: reuse annotate
#       name: Check and fix copyright headers with reuse annotate
#       entry: ./scripts/run_reuse_annotate.sh
#       language: system
#       pass_filenames: false
