---
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-FileCopyrightText: 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

#test

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c   # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: devcontainer-lock.json
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b # 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 38980559e3a605691d6579f96222c30778e5a69e # 3.0.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: reuse annotate
        name: Check and fix copyright headers with reuse annotate
        entry: ./scripts/run_reuse_annotate.sh
        language: unsupported_script
        pass_filenames: false
