# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

version = 1

[[annotations]]
path = [".devcontainer/*.json",
        "src/s-core-devcontainer/.devcontainer/*.json",
        "src/s-core-devcontainer/.devcontainer/s-core-local/devcontainer-feature.json",
        "src/s-core-devcontainer/.devcontainer/bazel-feature/devcontainer-feature.json",
        "src/s-core-devcontainer/manifest.json"
        ]
SPDX-FileCopyrightText = "Copyright (c) 2026 Contributors to the Eclipse Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["resources/reopen_in_container.png",
        "resources/devcontainer_success.png"
        ]
SPDX-FileCopyrightText = "Copyright (c) 2026 Contributors to the Eclipse Foundation"
SPDX-License-Identifier = "Apache-2.0"
